USE dbGun
GO
CREATE TRIGGER tr_insere_curso_basico ON dbo.tb_funcionario AFTER INSERT
AS
BEGIN
	DECLARE @matricula int

	--BUSCAR A MATRÍCULA QUE ACABOU DE SER ADICIONADA NA TB_FUNCIONARIO
	SELECT @matricula = INSERTED.mat_func FROM INSERTED

	--INSERE A NOVA MATRÍCULA + O CÓDIGO CORRESPONDENTE AO CURSO OBRIGATÓRIO (8)
	--NA TABELA TB_FUNC_ESP
	INSERT INTO dbo.tb_func_esp VALUES (@matricula, 8)
END